// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.3
// source: user.cgi.proto

package cgi

import (
	data "github.com/iegad/mmo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加用户信息
type AddUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *data.UserInfo `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
}

func (x *AddUserInfoReq) Reset() {
	*x = AddUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserInfoReq) ProtoMessage() {}

func (x *AddUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserInfoReq.ProtoReflect.Descriptor instead.
func (*AddUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserInfoReq) GetUserInfo() *data.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type AddUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserInfo *data.UserInfo `protobuf:"bytes,2,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
}

func (x *AddUserInfoRsp) Reset() {
	*x = AddUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserInfoRsp) ProtoMessage() {}

func (x *AddUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserInfoRsp.ProtoReflect.Descriptor instead.
func (*AddUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddUserInfoRsp) GetUserInfo() *data.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// 批量添加用户信息
type AddUserListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserList []*data.UserInfo `protobuf:"bytes,1,rep,name=UserList,proto3" json:"UserList,omitempty"`
}

func (x *AddUserListReq) Reset() {
	*x = AddUserListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserListReq) ProtoMessage() {}

func (x *AddUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserListReq.ProtoReflect.Descriptor instead.
func (*AddUserListReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{2}
}

func (x *AddUserListReq) GetUserList() []*data.UserInfo {
	if x != nil {
		return x.UserList
	}
	return nil
}

type AdduserListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32            `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserList []*data.UserInfo `protobuf:"bytes,2,rep,name=UserList,proto3" json:"UserList,omitempty"`
}

func (x *AdduserListRsp) Reset() {
	*x = AdduserListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdduserListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdduserListRsp) ProtoMessage() {}

func (x *AdduserListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdduserListRsp.ProtoReflect.Descriptor instead.
func (*AdduserListRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{3}
}

func (x *AdduserListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdduserListRsp) GetUserList() []*data.UserInfo {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 修改用户信息
type ModifyUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *data.UserInfo `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
}

func (x *ModifyUserInfoReq) Reset() {
	*x = ModifyUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserInfoReq) ProtoMessage() {}

func (x *ModifyUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserInfoReq.ProtoReflect.Descriptor instead.
func (*ModifyUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyUserInfoReq) GetUserInfo() *data.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ModifyUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserInfo *data.UserInfo `protobuf:"bytes,2,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
}

func (x *ModifyUserInfoRsp) Reset() {
	*x = ModifyUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserInfoRsp) ProtoMessage() {}

func (x *ModifyUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserInfoRsp.ProtoReflect.Descriptor instead.
func (*ModifyUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{5}
}

func (x *ModifyUserInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ModifyUserInfoRsp) GetUserInfo() *data.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// 移除用户信息
type RemoveUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIDs []int64 `protobuf:"varint,1,rep,packed,name=UserIDs,proto3" json:"UserIDs,omitempty"`
}

func (x *RemoveUserInfoReq) Reset() {
	*x = RemoveUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserInfoReq) ProtoMessage() {}

func (x *RemoveUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserInfoReq.ProtoReflect.Descriptor instead.
func (*RemoveUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveUserInfoReq) GetUserIDs() []int64 {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type RemoveUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	AffectedRows int32 `protobuf:"varint,2,opt,name=AffectedRows,proto3" json:"AffectedRows,omitempty"`
}

func (x *RemoveUserInfoRsp) Reset() {
	*x = RemoveUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserInfoRsp) ProtoMessage() {}

func (x *RemoveUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserInfoRsp.ProtoReflect.Descriptor instead.
func (*RemoveUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveUserInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoveUserInfoRsp) GetAffectedRows() int32 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

// 查询用户信息
type QueryUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNum      string `protobuf:"bytes,3,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"`
	Gender        int32  `protobuf:"varint,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	CreateTimeBeg int64  `protobuf:"varint,5,opt,name=CreateTimeBeg,proto3" json:"CreateTimeBeg,omitempty"`
	CreateTimeEnd int64  `protobuf:"varint,6,opt,name=CreateTimeEnd,proto3" json:"CreateTimeEnd,omitempty"`
	LastUpdateBeg int64  `protobuf:"varint,7,opt,name=LastUpdateBeg,proto3" json:"LastUpdateBeg,omitempty"`
	LastUpdateEnd int64  `protobuf:"varint,8,opt,name=LastUpdateEnd,proto3" json:"LastUpdateEnd,omitempty"`
	Offset        int64  `protobuf:"varint,9,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int64  `protobuf:"varint,10,opt,name=Limit,proto3" json:"Limit,omitempty"`
	OrderBy       string `protobuf:"bytes,11,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	Desc          bool   `protobuf:"varint,12,opt,name=Desc,proto3" json:"Desc,omitempty"`
}

func (x *QueryUserInfoReq) Reset() {
	*x = QueryUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserInfoReq) ProtoMessage() {}

func (x *QueryUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserInfoReq.ProtoReflect.Descriptor instead.
func (*QueryUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{8}
}

func (x *QueryUserInfoReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryUserInfoReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *QueryUserInfoReq) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *QueryUserInfoReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *QueryUserInfoReq) GetCreateTimeBeg() int64 {
	if x != nil {
		return x.CreateTimeBeg
	}
	return 0
}

func (x *QueryUserInfoReq) GetCreateTimeEnd() int64 {
	if x != nil {
		return x.CreateTimeEnd
	}
	return 0
}

func (x *QueryUserInfoReq) GetLastUpdateBeg() int64 {
	if x != nil {
		return x.LastUpdateBeg
	}
	return 0
}

func (x *QueryUserInfoReq) GetLastUpdateEnd() int64 {
	if x != nil {
		return x.LastUpdateEnd
	}
	return 0
}

func (x *QueryUserInfoReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryUserInfoReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryUserInfoReq) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *QueryUserInfoReq) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type QueryUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32            `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Total    int64            `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	UserList []*data.UserInfo `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList,omitempty"`
}

func (x *QueryUserInfoRsp) Reset() {
	*x = QueryUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserInfoRsp) ProtoMessage() {}

func (x *QueryUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserInfoRsp.ProtoReflect.Descriptor instead.
func (*QueryUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{9}
}

func (x *QueryUserInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryUserInfoRsp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryUserInfoRsp) GetUserList() []*data.UserInfo {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 判断用户是否存在
type ExistsUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *ExistsUserInfoReq) Reset() {
	*x = ExistsUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsUserInfoReq) ProtoMessage() {}

func (x *ExistsUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsUserInfoReq.ProtoReflect.Descriptor instead.
func (*ExistsUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{10}
}

func (x *ExistsUserInfoReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ExistsUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *ExistsUserInfoRsp) Reset() {
	*x = ExistsUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsUserInfoRsp) ProtoMessage() {}

func (x *ExistsUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsUserInfoRsp.ProtoReflect.Descriptor instead.
func (*ExistsUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{11}
}

func (x *ExistsUserInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 设置用户会话
type SetUserSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSession *data.UserSession `protobuf:"bytes,1,opt,name=UserSession,proto3" json:"UserSession,omitempty"`
}

func (x *SetUserSessionReq) Reset() {
	*x = SetUserSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserSessionReq) ProtoMessage() {}

func (x *SetUserSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserSessionReq.ProtoReflect.Descriptor instead.
func (*SetUserSessionReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{12}
}

func (x *SetUserSessionReq) GetUserSession() *data.UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

type SetUserSessionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserSession *data.UserSession `protobuf:"bytes,2,opt,name=UserSession,proto3" json:"UserSession,omitempty"`
}

func (x *SetUserSessionRsp) Reset() {
	*x = SetUserSessionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserSessionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserSessionRsp) ProtoMessage() {}

func (x *SetUserSessionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserSessionRsp.ProtoReflect.Descriptor instead.
func (*SetUserSessionRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserSessionRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetUserSessionRsp) GetUserSession() *data.UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

// 获取用户会话
type GetUserSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *GetUserSessionReq) Reset() {
	*x = GetUserSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionReq) ProtoMessage() {}

func (x *GetUserSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionReq.ProtoReflect.Descriptor instead.
func (*GetUserSessionReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserSessionReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetUserSessionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserSession *data.UserSession `protobuf:"bytes,2,opt,name=UserSession,proto3" json:"UserSession,omitempty"`
}

func (x *GetUserSessionRsp) Reset() {
	*x = GetUserSessionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSessionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionRsp) ProtoMessage() {}

func (x *GetUserSessionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionRsp.ProtoReflect.Descriptor instead.
func (*GetUserSessionRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserSessionRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserSessionRsp) GetUserSession() *data.UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

// 移除用户会话
type RemoveUserSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Token  []byte `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RemoveUserSessionReq) Reset() {
	*x = RemoveUserSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserSessionReq) ProtoMessage() {}

func (x *RemoveUserSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserSessionReq.ProtoReflect.Descriptor instead.
func (*RemoveUserSessionReq) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveUserSessionReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RemoveUserSessionReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type RemoveUserSessionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserSession *data.UserSession `protobuf:"bytes,2,opt,name=UserSession,proto3" json:"UserSession,omitempty"`
}

func (x *RemoveUserSessionRsp) Reset() {
	*x = RemoveUserSessionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_cgi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserSessionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserSessionRsp) ProtoMessage() {}

func (x *RemoveUserSessionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_cgi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserSessionRsp.ProtoReflect.Descriptor instead.
func (*RemoveUserSessionRsp) Descriptor() ([]byte, []int) {
	return file_user_cgi_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveUserSessionRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoveUserSessionRsp) GetUserSession() *data.UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

var File_user_cgi_proto protoreflect.FileDescriptor

var file_user_cgi_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x63, 0x67, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x63, 0x67, 0x69, 0x1a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x50, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3c, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x75, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x53, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2d, 0x0a, 0x11,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x73, 0x22, 0x4b, 0x0a, 0x11, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x52, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x41, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x22, 0xe8, 0x02, 0x0a, 0x10, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x24, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x65, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x42, 0x65, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x4c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65,
	0x67, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44,
	0x65, 0x73, 0x63, 0x22, 0x68, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a,
	0x11, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x11, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x48, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a,
	0x11, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x33, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5f, 0x0a, 0x14,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x20, 0x5a,
	0x18, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x65, 0x67, 0x61,
	0x64, 0x2f, 0x6d, 0x6d, 0x6f, 0x2f, 0x63, 0x67, 0x69, 0xaa, 0x02, 0x03, 0x63, 0x67, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_cgi_proto_rawDescOnce sync.Once
	file_user_cgi_proto_rawDescData = file_user_cgi_proto_rawDesc
)

func file_user_cgi_proto_rawDescGZIP() []byte {
	file_user_cgi_proto_rawDescOnce.Do(func() {
		file_user_cgi_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_cgi_proto_rawDescData)
	})
	return file_user_cgi_proto_rawDescData
}

var file_user_cgi_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_user_cgi_proto_goTypes = []interface{}{
	(*AddUserInfoReq)(nil),       // 0: cgi.AddUserInfoReq
	(*AddUserInfoRsp)(nil),       // 1: cgi.AddUserInfoRsp
	(*AddUserListReq)(nil),       // 2: cgi.AddUserListReq
	(*AdduserListRsp)(nil),       // 3: cgi.AdduserListRsp
	(*ModifyUserInfoReq)(nil),    // 4: cgi.ModifyUserInfoReq
	(*ModifyUserInfoRsp)(nil),    // 5: cgi.ModifyUserInfoRsp
	(*RemoveUserInfoReq)(nil),    // 6: cgi.RemoveUserInfoReq
	(*RemoveUserInfoRsp)(nil),    // 7: cgi.RemoveUserInfoRsp
	(*QueryUserInfoReq)(nil),     // 8: cgi.QueryUserInfoReq
	(*QueryUserInfoRsp)(nil),     // 9: cgi.QueryUserInfoRsp
	(*ExistsUserInfoReq)(nil),    // 10: cgi.ExistsUserInfoReq
	(*ExistsUserInfoRsp)(nil),    // 11: cgi.ExistsUserInfoRsp
	(*SetUserSessionReq)(nil),    // 12: cgi.SetUserSessionReq
	(*SetUserSessionRsp)(nil),    // 13: cgi.SetUserSessionRsp
	(*GetUserSessionReq)(nil),    // 14: cgi.GetUserSessionReq
	(*GetUserSessionRsp)(nil),    // 15: cgi.GetUserSessionRsp
	(*RemoveUserSessionReq)(nil), // 16: cgi.RemoveUserSessionReq
	(*RemoveUserSessionRsp)(nil), // 17: cgi.RemoveUserSessionRsp
	(*data.UserInfo)(nil),        // 18: data.UserInfo
	(*data.UserSession)(nil),     // 19: data.UserSession
}
var file_user_cgi_proto_depIdxs = []int32{
	18, // 0: cgi.AddUserInfoReq.UserInfo:type_name -> data.UserInfo
	18, // 1: cgi.AddUserInfoRsp.UserInfo:type_name -> data.UserInfo
	18, // 2: cgi.AddUserListReq.UserList:type_name -> data.UserInfo
	18, // 3: cgi.AdduserListRsp.UserList:type_name -> data.UserInfo
	18, // 4: cgi.ModifyUserInfoReq.UserInfo:type_name -> data.UserInfo
	18, // 5: cgi.ModifyUserInfoRsp.UserInfo:type_name -> data.UserInfo
	18, // 6: cgi.QueryUserInfoRsp.UserList:type_name -> data.UserInfo
	19, // 7: cgi.SetUserSessionReq.UserSession:type_name -> data.UserSession
	19, // 8: cgi.SetUserSessionRsp.UserSession:type_name -> data.UserSession
	19, // 9: cgi.GetUserSessionRsp.UserSession:type_name -> data.UserSession
	19, // 10: cgi.RemoveUserSessionRsp.UserSession:type_name -> data.UserSession
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_user_cgi_proto_init() }
func file_user_cgi_proto_init() {
	if File_user_cgi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_cgi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdduserListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistsUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistsUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserSessionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSessionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_cgi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserSessionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_cgi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_cgi_proto_goTypes,
		DependencyIndexes: file_user_cgi_proto_depIdxs,
		MessageInfos:      file_user_cgi_proto_msgTypes,
	}.Build()
	File_user_cgi_proto = out.File
	file_user_cgi_proto_rawDesc = nil
	file_user_cgi_proto_goTypes = nil
	file_user_cgi_proto_depIdxs = nil
}
