// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.3
// source: center.proto

package netpro

import (
	data "github.com/iegad/mmo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取验证码
type GetVCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNum string `protobuf:"bytes,1,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *GetVCodeReq) Reset() {
	*x = GetVCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVCodeReq) ProtoMessage() {}

func (x *GetVCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVCodeReq.ProtoReflect.Descriptor instead.
func (*GetVCodeReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{0}
}

func (x *GetVCodeReq) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *GetVCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetVCodeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *GetVCodeRsp) Reset() {
	*x = GetVCodeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVCodeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVCodeRsp) ProtoMessage() {}

func (x *GetVCodeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVCodeRsp.ProtoReflect.Descriptor instead.
func (*GetVCodeRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{1}
}

func (x *GetVCodeRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 注销用户
type UserUnregistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PhoneNum string `protobuf:"bytes,2,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	VCode    int32  `protobuf:"varint,4,opt,name=VCode,proto3" json:"VCode,omitempty"`
}

func (x *UserUnregistReq) Reset() {
	*x = UserUnregistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUnregistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnregistReq) ProtoMessage() {}

func (x *UserUnregistReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnregistReq.ProtoReflect.Descriptor instead.
func (*UserUnregistReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{2}
}

func (x *UserUnregistReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserUnregistReq) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *UserUnregistReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUnregistReq) GetVCode() int32 {
	if x != nil {
		return x.VCode
	}
	return 0
}

type UserUnregistRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *UserUnregistRsp) Reset() {
	*x = UserUnregistRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUnregistRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnregistRsp) ProtoMessage() {}

func (x *UserUnregistRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnregistRsp.ProtoReflect.Descriptor instead.
func (*UserUnregistRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{3}
}

func (x *UserUnregistRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 用户登录
type UserLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNum   string `protobuf:"bytes,1,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	VCode      int32  `protobuf:"varint,3,opt,name=VCode,proto3" json:"VCode,omitempty"`
	UserID     int64  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	DeviceCode []byte `protobuf:"bytes,5,opt,name=DeviceCode,proto3" json:"DeviceCode,omitempty"`
	Token      []byte `protobuf:"bytes,6,opt,name=Token,proto3" json:"Token,omitempty"`
	OSType     int32  `protobuf:"varint,7,opt,name=OSType,proto3" json:"OSType,omitempty"` // 1:  iOS, 2: android
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{4}
}

func (x *UserLoginReq) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *UserLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginReq) GetVCode() int32 {
	if x != nil {
		return x.VCode
	}
	return 0
}

func (x *UserLoginReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserLoginReq) GetDeviceCode() []byte {
	if x != nil {
		return x.DeviceCode
	}
	return nil
}

func (x *UserLoginReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *UserLoginReq) GetOSType() int32 {
	if x != nil {
		return x.OSType
	}
	return 0
}

type UserLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserInfo    *data.UserInfo    `protobuf:"bytes,2,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	UserSession *data.UserSession `protobuf:"bytes,3,opt,name=UserSession,proto3" json:"UserSession,omitempty"`
}

func (x *UserLoginRsp) Reset() {
	*x = UserLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRsp) ProtoMessage() {}

func (x *UserLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRsp.ProtoReflect.Descriptor instead.
func (*UserLoginRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{5}
}

func (x *UserLoginRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserLoginRsp) GetUserInfo() *data.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *UserLoginRsp) GetUserSession() *data.UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

// 用户登出
type UserLogoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Token  []byte `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *UserLogoutReq) Reset() {
	*x = UserLogoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogoutReq) ProtoMessage() {}

func (x *UserLogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogoutReq.ProtoReflect.Descriptor instead.
func (*UserLogoutReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{6}
}

func (x *UserLogoutReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserLogoutReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type UserLogoutRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *UserLogoutRsp) Reset() {
	*x = UserLogoutRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLogoutRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogoutRsp) ProtoMessage() {}

func (x *UserLogoutRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogoutRsp.ProtoReflect.Descriptor instead.
func (*UserLogoutRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{7}
}

func (x *UserLogoutRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 修改用户
type ModifyUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *data.UserInfo `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	Token    []byte         `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *ModifyUserInfoReq) Reset() {
	*x = ModifyUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserInfoReq) ProtoMessage() {}

func (x *ModifyUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserInfoReq.ProtoReflect.Descriptor instead.
func (*ModifyUserInfoReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyUserInfoReq) GetUserInfo() *data.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *ModifyUserInfoReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ModifyUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserInfo *data.UserInfo `protobuf:"bytes,2,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
}

func (x *ModifyUserInfoRsp) Reset() {
	*x = ModifyUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserInfoRsp) ProtoMessage() {}

func (x *ModifyUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserInfoRsp.ProtoReflect.Descriptor instead.
func (*ModifyUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyUserInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ModifyUserInfoRsp) GetUserInfo() *data.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type SearchUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PhoneNum string `protobuf:"bytes,2,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
}

func (x *SearchUserReq) Reset() {
	*x = SearchUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserReq) ProtoMessage() {}

func (x *SearchUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserReq.ProtoReflect.Descriptor instead.
func (*SearchUserReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUserReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SearchUserReq) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *SearchUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SearchUserReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type SearchUserRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	DataList *data.UserInfo `protobuf:"bytes,2,opt,name=DataList,proto3" json:"DataList,omitempty"`
}

func (x *SearchUserRsp) Reset() {
	*x = SearchUserRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserRsp) ProtoMessage() {}

func (x *SearchUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserRsp.ProtoReflect.Descriptor instead.
func (*SearchUserRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{11}
}

func (x *SearchUserRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchUserRsp) GetDataList() *data.UserInfo {
	if x != nil {
		return x.DataList
	}
	return nil
}

// 创建游戏人物
type CreateCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     []byte          `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Charactor *data.Charactor `protobuf:"bytes,2,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *CreateCharactorReq) Reset() {
	*x = CreateCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharactorReq) ProtoMessage() {}

func (x *CreateCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharactorReq.ProtoReflect.Descriptor instead.
func (*CreateCharactorReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCharactorReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateCharactorReq) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

type CreateCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32           `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Charactor *data.Charactor `protobuf:"bytes,2,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *CreateCharactorRsp) Reset() {
	*x = CreateCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharactorRsp) ProtoMessage() {}

func (x *CreateCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharactorRsp.ProtoReflect.Descriptor instead.
func (*CreateCharactorRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCharactorRsp) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

// 修改游戏人物
type ModifyCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     []byte          `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Charactor *data.Charactor `protobuf:"bytes,2,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *ModifyCharactorReq) Reset() {
	*x = ModifyCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyCharactorReq) ProtoMessage() {}

func (x *ModifyCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyCharactorReq.ProtoReflect.Descriptor instead.
func (*ModifyCharactorReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{14}
}

func (x *ModifyCharactorReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ModifyCharactorReq) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

type ModifyCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32           `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Charactor *data.Charactor `protobuf:"bytes,2,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *ModifyCharactorRsp) Reset() {
	*x = ModifyCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyCharactorRsp) ProtoMessage() {}

func (x *ModifyCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyCharactorRsp.ProtoReflect.Descriptor instead.
func (*ModifyCharactorRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{15}
}

func (x *ModifyCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ModifyCharactorRsp) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

// 删除游戏人物
type RemoveCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CharID int64  `protobuf:"varint,2,opt,name=CharID,proto3" json:"CharID,omitempty"`
	Token  []byte `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RemoveCharactorReq) Reset() {
	*x = RemoveCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCharactorReq) ProtoMessage() {}

func (x *RemoveCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCharactorReq.ProtoReflect.Descriptor instead.
func (*RemoveCharactorReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveCharactorReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RemoveCharactorReq) GetCharID() int64 {
	if x != nil {
		return x.CharID
	}
	return 0
}

func (x *RemoveCharactorReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type RemoveCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *RemoveCharactorRsp) Reset() {
	*x = RemoveCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCharactorRsp) ProtoMessage() {}

func (x *RemoveCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCharactorRsp.ProtoReflect.Descriptor instead.
func (*RemoveCharactorRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 查询游戏人物
type SearchCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CharID        int64  `protobuf:"varint,2,opt,name=CharID,proto3" json:"CharID,omitempty"`
	CharactorName string `protobuf:"bytes,3,opt,name=CharactorName,proto3" json:"CharactorName,omitempty"`
}

func (x *SearchCharactorReq) Reset() {
	*x = SearchCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCharactorReq) ProtoMessage() {}

func (x *SearchCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCharactorReq.ProtoReflect.Descriptor instead.
func (*SearchCharactorReq) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{18}
}

func (x *SearchCharactorReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SearchCharactorReq) GetCharID() int64 {
	if x != nil {
		return x.CharID
	}
	return 0
}

func (x *SearchCharactorReq) GetCharactorName() string {
	if x != nil {
		return x.CharactorName
	}
	return ""
}

type SearchCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	DataList []*data.Charactor `protobuf:"bytes,2,rep,name=DataList,proto3" json:"DataList,omitempty"`
}

func (x *SearchCharactorRsp) Reset() {
	*x = SearchCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCharactorRsp) ProtoMessage() {}

func (x *SearchCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCharactorRsp.ProtoReflect.Descriptor instead.
func (*SearchCharactorRsp) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{19}
}

func (x *SearchCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchCharactorRsp) GetDataList() []*data.Charactor {
	if x != nil {
		return x.DataList
	}
	return nil
}

var File_center_proto protoreflect.FileDescriptor

var file_center_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x1a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x21,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x71, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x0c,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x3d, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x23, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x55, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x53, 0x0a, 0x11, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x75, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x4e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x22, 0x57, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a,
	0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x59, 0x0a, 0x12,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x57, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x22, 0x5a, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x43, 0x68, 0x61, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x43, 0x68, 0x61, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28, 0x0a, 0x12,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x6a, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x68, 0x61, 0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x55, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x26, 0x5a, 0x1b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x65, 0x67, 0x61, 0x64, 0x2f, 0x6d, 0x6d,
	0x6f, 0x2f, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0xaa, 0x02, 0x06, 0x6e, 0x65, 0x74, 0x70, 0x72,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_center_proto_rawDescOnce sync.Once
	file_center_proto_rawDescData = file_center_proto_rawDesc
)

func file_center_proto_rawDescGZIP() []byte {
	file_center_proto_rawDescOnce.Do(func() {
		file_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_center_proto_rawDescData)
	})
	return file_center_proto_rawDescData
}

var file_center_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_center_proto_goTypes = []interface{}{
	(*GetVCodeReq)(nil),        // 0: netpro.GetVCodeReq
	(*GetVCodeRsp)(nil),        // 1: netpro.GetVCodeRsp
	(*UserUnregistReq)(nil),    // 2: netpro.UserUnregistReq
	(*UserUnregistRsp)(nil),    // 3: netpro.UserUnregistRsp
	(*UserLoginReq)(nil),       // 4: netpro.UserLoginReq
	(*UserLoginRsp)(nil),       // 5: netpro.UserLoginRsp
	(*UserLogoutReq)(nil),      // 6: netpro.UserLogoutReq
	(*UserLogoutRsp)(nil),      // 7: netpro.UserLogoutRsp
	(*ModifyUserInfoReq)(nil),  // 8: netpro.ModifyUserInfoReq
	(*ModifyUserInfoRsp)(nil),  // 9: netpro.ModifyUserInfoRsp
	(*SearchUserReq)(nil),      // 10: netpro.SearchUserReq
	(*SearchUserRsp)(nil),      // 11: netpro.SearchUserRsp
	(*CreateCharactorReq)(nil), // 12: netpro.CreateCharactorReq
	(*CreateCharactorRsp)(nil), // 13: netpro.CreateCharactorRsp
	(*ModifyCharactorReq)(nil), // 14: netpro.ModifyCharactorReq
	(*ModifyCharactorRsp)(nil), // 15: netpro.ModifyCharactorRsp
	(*RemoveCharactorReq)(nil), // 16: netpro.RemoveCharactorReq
	(*RemoveCharactorRsp)(nil), // 17: netpro.RemoveCharactorRsp
	(*SearchCharactorReq)(nil), // 18: netpro.SearchCharactorReq
	(*SearchCharactorRsp)(nil), // 19: netpro.SearchCharactorRsp
	(*data.UserInfo)(nil),      // 20: data.UserInfo
	(*data.UserSession)(nil),   // 21: data.UserSession
	(*data.Charactor)(nil),     // 22: data.Charactor
}
var file_center_proto_depIdxs = []int32{
	20, // 0: netpro.UserLoginRsp.UserInfo:type_name -> data.UserInfo
	21, // 1: netpro.UserLoginRsp.UserSession:type_name -> data.UserSession
	20, // 2: netpro.ModifyUserInfoReq.UserInfo:type_name -> data.UserInfo
	20, // 3: netpro.ModifyUserInfoRsp.UserInfo:type_name -> data.UserInfo
	20, // 4: netpro.SearchUserRsp.DataList:type_name -> data.UserInfo
	22, // 5: netpro.CreateCharactorReq.Charactor:type_name -> data.Charactor
	22, // 6: netpro.CreateCharactorRsp.Charactor:type_name -> data.Charactor
	22, // 7: netpro.ModifyCharactorReq.Charactor:type_name -> data.Charactor
	22, // 8: netpro.ModifyCharactorRsp.Charactor:type_name -> data.Charactor
	22, // 9: netpro.SearchCharactorRsp.DataList:type_name -> data.Charactor
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_center_proto_init() }
func file_center_proto_init() {
	if File_center_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_center_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVCodeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUnregistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUnregistRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLogoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLogoutRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchUserRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_center_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_center_proto_goTypes,
		DependencyIndexes: file_center_proto_depIdxs,
		MessageInfos:      file_center_proto_msgTypes,
	}.Build()
	File_center_proto = out.File
	file_center_proto_rawDesc = nil
	file_center_proto_goTypes = nil
	file_center_proto_depIdxs = nil
}
