// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.3
// source: charactor.cgi.proto

package cgi

import (
	data "github.com/iegad/mmo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建人物
type AddCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charactor *data.Charactor `protobuf:"bytes,1,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *AddCharactorReq) Reset() {
	*x = AddCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCharactorReq) ProtoMessage() {}

func (x *AddCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCharactorReq.ProtoReflect.Descriptor instead.
func (*AddCharactorReq) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{0}
}

func (x *AddCharactorReq) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

type AddCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32           `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Charactor *data.Charactor `protobuf:"bytes,2,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *AddCharactorRsp) Reset() {
	*x = AddCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCharactorRsp) ProtoMessage() {}

func (x *AddCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCharactorRsp.ProtoReflect.Descriptor instead.
func (*AddCharactorRsp) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{1}
}

func (x *AddCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddCharactorRsp) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

// 修改人物
type ModifyCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charactor *data.Charactor `protobuf:"bytes,1,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *ModifyCharactorReq) Reset() {
	*x = ModifyCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyCharactorReq) ProtoMessage() {}

func (x *ModifyCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyCharactorReq.ProtoReflect.Descriptor instead.
func (*ModifyCharactorReq) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyCharactorReq) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

type ModifyCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32           `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Charactor *data.Charactor `protobuf:"bytes,2,opt,name=Charactor,proto3" json:"Charactor,omitempty"`
}

func (x *ModifyCharactorRsp) Reset() {
	*x = ModifyCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyCharactorRsp) ProtoMessage() {}

func (x *ModifyCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyCharactorRsp.ProtoReflect.Descriptor instead.
func (*ModifyCharactorRsp) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ModifyCharactorRsp) GetCharactor() *data.Charactor {
	if x != nil {
		return x.Charactor
	}
	return nil
}

// 获取人物
type QueryCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int64         `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CharID        int64         `protobuf:"varint,2,opt,name=CharID,proto3" json:"CharID,omitempty"`
	Nickname      string        `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Role          data.RoleType `protobuf:"varint,4,opt,name=Role,proto3,enum=data.RoleType" json:"Role,omitempty"`
	Gender        int32         `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	CreateTimeBeg int64         `protobuf:"varint,6,opt,name=CreateTimeBeg,proto3" json:"CreateTimeBeg,omitempty"`
	CreateTimeEnd int64         `protobuf:"varint,7,opt,name=CreateTimeEnd,proto3" json:"CreateTimeEnd,omitempty"`
	LastUpdateBeg int64         `protobuf:"varint,8,opt,name=LastUpdateBeg,proto3" json:"LastUpdateBeg,omitempty"`
	LastUpdateEnd int64         `protobuf:"varint,9,opt,name=LastUpdateEnd,proto3" json:"LastUpdateEnd,omitempty"`
	Offset        int64         `protobuf:"varint,10,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int64         `protobuf:"varint,11,opt,name=Limit,proto3" json:"Limit,omitempty"`
	OrderBy       string        `protobuf:"bytes,12,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	Desc          bool          `protobuf:"varint,13,opt,name=Desc,proto3" json:"Desc,omitempty"`
}

func (x *QueryCharactorReq) Reset() {
	*x = QueryCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCharactorReq) ProtoMessage() {}

func (x *QueryCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCharactorReq.ProtoReflect.Descriptor instead.
func (*QueryCharactorReq) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{4}
}

func (x *QueryCharactorReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryCharactorReq) GetCharID() int64 {
	if x != nil {
		return x.CharID
	}
	return 0
}

func (x *QueryCharactorReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *QueryCharactorReq) GetRole() data.RoleType {
	if x != nil {
		return x.Role
	}
	return data.RoleType(0)
}

func (x *QueryCharactorReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *QueryCharactorReq) GetCreateTimeBeg() int64 {
	if x != nil {
		return x.CreateTimeBeg
	}
	return 0
}

func (x *QueryCharactorReq) GetCreateTimeEnd() int64 {
	if x != nil {
		return x.CreateTimeEnd
	}
	return 0
}

func (x *QueryCharactorReq) GetLastUpdateBeg() int64 {
	if x != nil {
		return x.LastUpdateBeg
	}
	return 0
}

func (x *QueryCharactorReq) GetLastUpdateEnd() int64 {
	if x != nil {
		return x.LastUpdateEnd
	}
	return 0
}

func (x *QueryCharactorReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryCharactorReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryCharactorReq) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *QueryCharactorReq) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type QueryCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	DataList []*data.Charactor `protobuf:"bytes,2,rep,name=DataList,proto3" json:"DataList,omitempty"`
	Total    int64             `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *QueryCharactorRsp) Reset() {
	*x = QueryCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCharactorRsp) ProtoMessage() {}

func (x *QueryCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCharactorRsp.ProtoReflect.Descriptor instead.
func (*QueryCharactorRsp) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{5}
}

func (x *QueryCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryCharactorRsp) GetDataList() []*data.Charactor {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *QueryCharactorRsp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 移除人物
type RemoveCharactorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RoleID int64 `protobuf:"varint,2,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *RemoveCharactorReq) Reset() {
	*x = RemoveCharactorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCharactorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCharactorReq) ProtoMessage() {}

func (x *RemoveCharactorReq) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCharactorReq.ProtoReflect.Descriptor instead.
func (*RemoveCharactorReq) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveCharactorReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RemoveCharactorReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

type RemoveCharactorRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	AffectedRows int32 `protobuf:"varint,2,opt,name=AffectedRows,proto3" json:"AffectedRows,omitempty"`
}

func (x *RemoveCharactorRsp) Reset() {
	*x = RemoveCharactorRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_charactor_cgi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCharactorRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCharactorRsp) ProtoMessage() {}

func (x *RemoveCharactorRsp) ProtoReflect() protoreflect.Message {
	mi := &file_charactor_cgi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCharactorRsp.ProtoReflect.Descriptor instead.
func (*RemoveCharactorRsp) Descriptor() ([]byte, []int) {
	return file_charactor_cgi_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveCharactorRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoveCharactorRsp) GetAffectedRows() int32 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

var File_charactor_cgi_proto protoreflect.FileDescriptor

var file_charactor_cgi_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x67, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x67, 0x69, 0x1a, 0x14, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x40, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x22, 0x54, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x2d,
	0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x57, 0x0a,
	0x12, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x8f, 0x03, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x68, 0x61, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x42, 0x65, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x65, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65,
	0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x65, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x4c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x22, 0x6a, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x2b, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0x44, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x4c, 0x0a, 0x12, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x52, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x41, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x42, 0x20, 0x5a, 0x18, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x65, 0x67, 0x61, 0x64, 0x2f, 0x6d, 0x6d, 0x6f,
	0x2f, 0x63, 0x67, 0x69, 0xaa, 0x02, 0x03, 0x63, 0x67, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_charactor_cgi_proto_rawDescOnce sync.Once
	file_charactor_cgi_proto_rawDescData = file_charactor_cgi_proto_rawDesc
)

func file_charactor_cgi_proto_rawDescGZIP() []byte {
	file_charactor_cgi_proto_rawDescOnce.Do(func() {
		file_charactor_cgi_proto_rawDescData = protoimpl.X.CompressGZIP(file_charactor_cgi_proto_rawDescData)
	})
	return file_charactor_cgi_proto_rawDescData
}

var file_charactor_cgi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_charactor_cgi_proto_goTypes = []interface{}{
	(*AddCharactorReq)(nil),    // 0: cgi.AddCharactorReq
	(*AddCharactorRsp)(nil),    // 1: cgi.AddCharactorRsp
	(*ModifyCharactorReq)(nil), // 2: cgi.ModifyCharactorReq
	(*ModifyCharactorRsp)(nil), // 3: cgi.ModifyCharactorRsp
	(*QueryCharactorReq)(nil),  // 4: cgi.QueryCharactorReq
	(*QueryCharactorRsp)(nil),  // 5: cgi.QueryCharactorRsp
	(*RemoveCharactorReq)(nil), // 6: cgi.RemoveCharactorReq
	(*RemoveCharactorRsp)(nil), // 7: cgi.RemoveCharactorRsp
	(*data.Charactor)(nil),     // 8: data.Charactor
	(data.RoleType)(0),         // 9: data.RoleType
}
var file_charactor_cgi_proto_depIdxs = []int32{
	8, // 0: cgi.AddCharactorReq.Charactor:type_name -> data.Charactor
	8, // 1: cgi.AddCharactorRsp.Charactor:type_name -> data.Charactor
	8, // 2: cgi.ModifyCharactorReq.Charactor:type_name -> data.Charactor
	8, // 3: cgi.ModifyCharactorRsp.Charactor:type_name -> data.Charactor
	9, // 4: cgi.QueryCharactorReq.Role:type_name -> data.RoleType
	8, // 5: cgi.QueryCharactorRsp.DataList:type_name -> data.Charactor
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_charactor_cgi_proto_init() }
func file_charactor_cgi_proto_init() {
	if File_charactor_cgi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_charactor_cgi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charactor_cgi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charactor_cgi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charactor_cgi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charactor_cgi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charactor_cgi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charactor_cgi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCharactorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_charactor_cgi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCharactorRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_charactor_cgi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charactor_cgi_proto_goTypes,
		DependencyIndexes: file_charactor_cgi_proto_depIdxs,
		MessageInfos:      file_charactor_cgi_proto_msgTypes,
	}.Build()
	File_charactor_cgi_proto = out.File
	file_charactor_cgi_proto_rawDesc = nil
	file_charactor_cgi_proto_goTypes = nil
	file_charactor_cgi_proto_depIdxs = nil
}
