CREATE DATABASE IF NOT EXISTS `DB_USER` DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `DB_USER`.`T_BASIC`(
  F_USER_ID     BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键, 自增ID',
  F_EMAIL       VARCHAR(50)  NULL                    COMMENT '邮箱',
  F_PHONE_NUM   VARCHAR(15)  NULL                    COMMENT '手机号',
  F_GENDER      TINYINT      NOT NULL DEFAULT 3      COMMENT '性别',
  F_NICKNAME    VARCHAR(8)   NOT NULL DEFAULT ''     COMMENT '昵称',
  F_AVATOR      VARCHAR(120) NOT NULL DEFAULT ''     COMMENT '头像',
  F_CREATE_TIME BIGINT       NOT NULL DEFAULT 0      COMMENT '创建时间',
  F_LAST_UPDATE BIGINT       NOT NULL DEFAULT 0      COMMENT '最后更新时间',
  F_VER_CODE    INT UNSIGNED NOT NULL DEFAULT 0      COMMENT '版本号',

  PRIMARY KEY (F_USER_ID),
  
  UNIQUE KEY (F_EMAIL),
  UNIQUE KEY (F_PHONE_NUM),

  KEY (F_GENDER),
  KEY (F_NICKNAME),
  KEY (F_CREATE_TIME),
  KEY (F_LAST_UPDATE),
  KEY (F_VER_CODE)
) COMMENT = '用户基础信息表' ENGINE = INNODB CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `DB_USER`.`T_PERSONAL`(
  F_USER_ID     BIGINT       NOT NULL           COMMENT '主键',
  F_NAME        VARCHAR(20)  NOT NULL           COMMENT '姓名',
  F_NATIONALITY VARCHAR(5)   NOT NULL           COMMENT '国籍',
  F_GENDER      TINYINT      NOT NULL           COMMENT '性别',
  F_BIRTH       BIGINT       NOT NULL           COMMENT '出生日期',
  F_ID          CHAR(18)     NOT NULL           COMMENT '身份证号',
  F_VER_CODE    INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '版本号',

  PRIMARY KEY(F_USER_ID),

  UNIQUE KEY (F_ID),

  KEY (F_NATIONALITY),
  KEY (F_GENDER),
  KEY (F_VER_CODE)
) COMMENT = '用户个人信息表' ENGINE = INNODB CHARSET = utf8mb4;